name: Run tests

on:
  push:
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      julia_versions: ${{ steps.set-matrix.outputs.julia_versions }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "dev" ]]; then
            echo 'julia_versions=["1.11", "1.12"]' >> $GITHUB_OUTPUT
          else
            echo 'julia_versions=["1.12"]' >> $GITHUB_OUTPUT
          fi

  call-ci:
    needs: configure
    uses: ./.github/workflows/reusable-ci.yml
    with:
      julia_versions: ${{ needs.configure.outputs.julia_versions }}
